import { Mods } from "@/lib/types/api";

export const ShortenedMods = {
  [Mods.NONE]: "NM",
  [Mods.NO_FAIL]: "NF",
  [Mods.EASY]: "EZ",
  [Mods.TOUCH_DEVICE]: "TD",
  [Mods.HIDDEN]: "HD",
  [Mods.HARD_ROCK]: "HR",
  [Mods.SUDDEN_DEATH]: "SD",
  [Mods.DOUBLE_TIME]: "DT",
  [Mods.RELAX]: "RX",
  [Mods.HALF_TIME]: "HT",
  [Mods.NIGHTCORE]: "NC",
  [Mods.FLASHLIGHT]: "FL",
  [Mods.AUTOPLAY]: "AT",
  [Mods.SPUN_OUT]: "SO",
  [Mods.RELAX2]: "AP",
  [Mods.PERFECT]: "PF",
  [Mods.KEY4]: "K4",
  [Mods.KEY5]: "K5",
  [Mods.KEY6]: "K6",
  [Mods.KEY7]: "K7",
  [Mods.KEY8]: "K8",
  [Mods.FADE_IN]: "FDIN",
  [Mods.RANDOM]: "RND",
  [Mods.CINEMA]: "CN",
  [Mods.TARGET]: "TA",
  [Mods.KEY9]: "K9",
  [Mods.KEY_COOP]: "KCP",
  [Mods.KEY1]: "K1",
  [Mods.KEY3]: "K3",
  [Mods.KEY2]: "K2",
  [Mods.SCORE_V2]: "V2",
};
