// This file is auto-generated by @hey-api/openapi-ts

export type AdminScoreResponse = {
  score: ScoreResponse;
  submission_status: SubmissionStatus;
  beatmap_status: BeatmapStatus;
  is_scoreable: boolean;
  score_hash?: string | null;
};

export type AdminScoresResponse = {
  scores: AdminScoreResponse[];
  total_count: number;
};

export type BeatmapEventResponse = {
  event_id: number;
  executor: UserResponse;
  type: BeatmapEventType;
  beatmapset_id: number;
  beatmapset: BeatmapSetResponse;
  beatmap_hash?: string | null;
  new_status?: BeatmapStatusWeb;
  created_at: string;
};

export enum BeatmapEventType {
  BEATMAP_SET_HYPED = "BeatmapSetHyped",
  BEATMAP_STATUS_CHANGED = "BeatmapStatusChanged",
  BEATMAP_SET_HYPE_CLEARED = "BeatmapSetHypeCleared",
}

export type BeatmapResponse = {
  id: number;
  beatmapset_id: number;
  hash: string;
  version: string;
  status: BeatmapStatusWeb;
  star_rating_osu: number;
  star_rating_taiko: number;
  star_rating_ctb: number;
  star_rating_mania: number;
  total_length: number;
  max_combo: number;
  accuracy?: number | null;
  ar?: number | null;
  bpm: number;
  convert: boolean;
  count_circles: number;
  count_sliders: number;
  count_spinners: number;
  cs: number;
  deleted_at?: string | null;
  drain?: number | null;
  hit_length: number;
  is_scoreable: boolean;
  is_ranked: boolean;
  last_updated: string;
  mode_int: number;
  mode: GameMode;
  ranked: number;
  title?: string | null;
  artist?: string | null;
  creator?: string | null;
  creator_id: number;
  beatmap_nominator_user?: UserResponse;
};

export type BeatmapSetEventsResponse = {
  events: BeatmapEventResponse[];
  total_count: number;
};

export type BeatmapSetHypeCountResponse = {
  current_hypes: number;
  required_hypes: number;
};

export type BeatmapSetResponse = {
  id: number;
  artist: string;
  title: string;
  creator: string;
  creator_id: number;
  status: BeatmapStatusWeb;
  last_updated: string;
  submitted_date: string;
  ranked_date?: string | null;
  video: boolean;
  beatmaps: BeatmapResponse[];
  description: string;
  genre: string;
  language: string;
  tags: string[];
  beatmap_nominator_user?: UserResponse;
  can_be_hyped: boolean;
};

export type BeatmapSetsResponse = {
  sets: BeatmapSetResponse[];
  total_count?: number | null;
};

export enum BeatmapStatus {
  PENDING = "Pending",
  NEEDS_UPDATE = "NeedsUpdate",
  RANKED = "Ranked",
  APPROVED = "Approved",
  QUALIFIED = "Qualified",
  LOVED = "Loved",
  UNKNOWN = "Unknown",
  NOT_SUBMITTED = "NotSubmitted",
}

export enum BeatmapStatusWeb {
  PENDING = "Pending",
  RANKED = "Ranked",
  APPROVED = "Approved",
  QUALIFIED = "Qualified",
  LOVED = "Loved",
  UNKNOWN = "Unknown",
  GRAVEYARD = "Graveyard",
  WIP = "Wip",
}

export type BulkScoreProcessingByFilterRequest = {
  action: ScoreTaskType;
  user_id: number;
  mode?: GameMode;
  mods?: Mods[] | null;
  submission_status?: SubmissionStatus;
  beatmap_status?: BeatmapStatus;
  submitted_from?: string | null;
  submitted_to?: string | null;
};

export type BulkScoreProcessingRequest = {
  score_ids: number[];
  action: ScoreTaskType;
};

export type BulkScoreProcessingResultResponse = {
  queued: number;
  skipped: number;
};

export type Category = {
  readonly medals: UserMedalResponse[];
};

export type ChangePasswordRequest = {
  current_password: string;
  new_password: string;
};

export type CountryChangeRequest = {
  new_country: CountryCode;
};

export enum CountryCode {
  XX = "XX",
  AD = "AD",
  AF = "AF",
  AI = "AI",
  AL = "AL",
  AM = "AM",
  AO = "AO",
  AQ = "AQ",
  AR = "AR",
  AS = "AS",
  AT = "AT",
  AU = "AU",
  AW = "AW",
  AZ = "AZ",
  BB = "BB",
  BD = "BD",
  BE = "BE",
  BF = "BF",
  BG = "BG",
  BH = "BH",
  BI = "BI",
  BJ = "BJ",
  BM = "BM",
  BO = "BO",
  BR = "BR",
  BS = "BS",
  BT = "BT",
  BV = "BV",
  BW = "BW",
  BY = "BY",
  BZ = "BZ",
  CA = "CA",
  CC = "CC",
  CF = "CF",
  CH = "CH",
  CK = "CK",
  CL = "CL",
  CM = "CM",
  CN = "CN",
  CO = "CO",
  CR = "CR",
  CU = "CU",
  CV = "CV",
  CX = "CX",
  CY = "CY",
  CZ = "CZ",
  DE = "DE",
  DJ = "DJ",
  DK = "DK",
  DM = "DM",
  DO = "DO",
  DZ = "DZ",
  EC = "EC",
  EE = "EE",
  EG = "EG",
  EH = "EH",
  ER = "ER",
  ES = "ES",
  ET = "ET",
  FI = "FI",
  FJ = "FJ",
  FK = "FK",
  FO = "FO",
  FR = "FR",
  GA = "GA",
  GB = "GB",
  GD = "GD",
  GE = "GE",
  GF = "GF",
  GH = "GH",
  GI = "GI",
  GL = "GL",
  GM = "GM",
  GN = "GN",
  GP = "GP",
  GQ = "GQ",
  GR = "GR",
  GT = "GT",
  GU = "GU",
  GW = "GW",
  GY = "GY",
  HK = "HK",
  HN = "HN",
  HR = "HR",
  HT = "HT",
  HU = "HU",
  ID = "ID",
  IE = "IE",
  IL = "IL",
  IN = "IN",
  IO = "IO",
  IQ = "IQ",
  IS = "IS",
  IT = "IT",
  JM = "JM",
  JO = "JO",
  JP = "JP",
  KE = "KE",
  KG = "KG",
  KH = "KH",
  KI = "KI",
  KM = "KM",
  KR = "KR",
  KW = "KW",
  KY = "KY",
  KZ = "KZ",
  LB = "LB",
  LI = "LI",
  LK = "LK",
  LR = "LR",
  LS = "LS",
  LT = "LT",
  LU = "LU",
  LV = "LV",
  MA = "MA",
  MC = "MC",
  MG = "MG",
  MH = "MH",
  ML = "ML",
  MM = "MM",
  MN = "MN",
  MP = "MP",
  MQ = "MQ",
  MR = "MR",
  MS = "MS",
  MT = "MT",
  MU = "MU",
  MV = "MV",
  MW = "MW",
  MX = "MX",
  MY = "MY",
  MZ = "MZ",
  NA = "NA",
  NC = "NC",
  NE = "NE",
  NF = "NF",
  NG = "NG",
  NI = "NI",
  NL = "NL",
  NO = "NO",
  NP = "NP",
  NR = "NR",
  NU = "NU",
  NZ = "NZ",
  OM = "OM",
  PA = "PA",
  PE = "PE",
  PF = "PF",
  PG = "PG",
  PH = "PH",
  PK = "PK",
  PL = "PL",
  PN = "PN",
  PR = "PR",
  PS = "PS",
  PT = "PT",
  PW = "PW",
  PY = "PY",
  QA = "QA",
  RE = "RE",
  RO = "RO",
  RU = "RU",
  RW = "RW",
  SA = "SA",
  SB = "SB",
  SC = "SC",
  SD = "SD",
  SE = "SE",
  SG = "SG",
  SI = "SI",
  SJ = "SJ",
  SK = "SK",
  SL = "SL",
  SM = "SM",
  SN = "SN",
  SO = "SO",
  SR = "SR",
  ST = "ST",
  SV = "SV",
  SZ = "SZ",
  TC = "TC",
  TD = "TD",
  TF = "TF",
  TG = "TG",
  TH = "TH",
  TJ = "TJ",
  TK = "TK",
  TM = "TM",
  TN = "TN",
  TO = "TO",
  TR = "TR",
  TT = "TT",
  TV = "TV",
  TW = "TW",
  TZ = "TZ",
  UA = "UA",
  UG = "UG",
  US = "US",
  UY = "UY",
  UZ = "UZ",
  VE = "VE",
  VN = "VN",
  VU = "VU",
  WF = "WF",
  WS = "WS",
  YE = "YE",
  YT = "YT",
  RS = "RS",
  ZA = "ZA",
  ZM = "ZM",
  ME = "ME",
  ZW = "ZW",
  AX = "AX",
  GG = "GG",
  IM = "IM",
  JE = "JE",
  MF = "MF",
}

export type CreateScoreProcessingTaskRequest = {
  score_id: number;
  action: ScoreTaskType;
};

export type CustomBeatmapStatusChangeResponse = {
  beatmap: BeatmapResponse;
  new_status: BeatmapStatusWeb;
  old_status: BeatmapStatusWeb;
  bat: UserResponse;
};

export type DifficultyAttributes = {
  aim?: number | null;
  aimDifficultStrainCount?: number | null;
  ar?: number | null;
  color?: number | null;
  flashlight?: number | null;
  greatHitWindow?: number | null;
  hp?: number | null;
  isConvert: boolean;
  maxCombo: number;
  mode: GameMode;
  monoStaminaFactor?: number | null;
  nCircles?: number | null;
  nDroplets?: number | null;
  nFruits?: number | null;
  nHoldNotes?: number | null;
  nLargeTicks?: number | null;
  nObjects?: number | null;
  nSliders?: number | null;
  nSpinners?: number | null;
  nTinyDroplets?: number | null;
  od?: number | null;
  okHitWindow?: number | null;
  peak?: number | null;
  rhythm?: number | null;
  sliderFactor?: number | null;
  speed?: number | null;
  speedDifficultStrainCount?: number | null;
  speedNoteCount?: number | null;
  stamina?: number | null;
  stars: number;
};

export type EditBeatmapsetFavouriteStatusRequest = {
  favourited: boolean;
};

export type EditDefaultGameModeRequest = {
  default_gamemode: GameMode;
};

export type EditDescriptionRequest = {
  description: string;
};

export type EditFriendshipStatusRequest = {
  action: UpdateFriendshipStatusAction;
};

export type EditHidePreviousUsernameRequest = {
  event_id: number;
  is_hidden: boolean;
};

export type EditIgnoreLoginDataRequest = {
  is_ignored: boolean;
};

export type EditUserMetadataRequest = {
  playstyle?: UserPlaystyle[] | null;
  location?: string | null;
  interest?: string | null;
  occupation?: string | null;
  telegram?: string | null;
  twitch?: string | null;
  twitter?: string | null;
  discord?: string | null;
  website?: string | null;
};

export type EditUserPrivilegeRequest = {
  privilege: UserPrivilege[];
};

export type EditUserRestrictionRequest = {
  is_restrict: boolean;
  restriction_reason?: string | null;
};

export type EventScoreProcessingListResponse = {
  events: EventScoreProcessingResponse[];
  total_count: number;
};

export type EventScoreProcessingResponse = {
  id: number;
  event_type: ScoreProcessingEventType;
  executor?: UserResponse;
  score_id?: number | null;
  task_id?: number | null;
  json_data?: string | null;
  created_at: string;
};

export type EventUserResponse = {
  id: number;
  user: UserResponse;
  event_type: UserEventType;
  ip: string;
  json_data: string;
  created_at: string;
};

export type EventUsersResponse = {
  events: EventUserResponse[];
  total_count: number;
};

export type FavouritedResponse = {
  favourited: boolean;
};

export type FollowersResponse = {
  followers: UserResponse[];
  total_count: number;
};

export type FriendStatusResponse = {
  is_following_you: boolean;
  is_followed_by_you: boolean;
};

export type FriendsResponse = {
  friends: UserResponse[];
  total_count: number;
};

export enum GameMode {
  STANDARD = "Standard",
  TAIKO = "Taiko",
  CATCH_THE_BEAT = "CatchTheBeat",
  MANIA = "Mania",
  RELAX_STANDARD = "RelaxStandard",
  RELAX_TAIKO = "RelaxTaiko",
  RELAX_CATCH_THE_BEAT = "RelaxCatchTheBeat",
  AUTOPILOT_STANDARD = "AutopilotStandard",
  SCORE_V2_STANDARD = "ScoreV2Standard",
  SCORE_V2_TAIKO = "ScoreV2Taiko",
  SCORE_V2_CATCH_THE_BEAT = "ScoreV2CatchTheBeat",
  SCORE_V2_MANIA = "ScoreV2Mania",
}

export type GradesResponse = {
  count_xh: number;
  count_x: number;
  count_sh: number;
  count_s: number;
  count_a: number;
  count_b: number;
  count_c: number;
  count_d: number;
};

export type HypedBeatmapSetResponse = {
  id: number;
  artist: string;
  title: string;
  creator: string;
  creator_id: number;
  status: BeatmapStatusWeb;
  last_updated: string;
  submitted_date: string;
  ranked_date?: string | null;
  video: boolean;
  beatmaps: BeatmapResponse[];
  description: string;
  genre: string;
  language: string;
  tags: string[];
  beatmap_nominator_user?: UserResponse;
  can_be_hyped: boolean;
  hypeCount: number;
};

export type HypedBeatmapSetsResponse = {
  sets: HypedBeatmapSetResponse[];
  total_count?: number | null;
};

export type InventoryItemResponse = {
  quantity: number;
  item_type: ItemType;
};

export enum ItemType {
  HYPE = "Hype",
}

export type LeaderboardResponse = {
  users: UserWithStats[];
  total_count: number;
};

export enum LeaderboardSortType {
  PP = "Pp",
  SCORE = "Score",
}

export type LimitsResponse = {
  message: string;
  rate_limits: RateLimits;
  beatmap_rate_limits: RateLimits;
};

export type MedalsResponse = {
  hush_hush: Category;
  beatmap_hunt: Category;
  mod_introduction: Category;
  skill: Category;
};

export enum Mods {
  NONE = "None",
  NO_FAIL = "NoFail",
  EASY = "Easy",
  TOUCH_DEVICE = "TouchDevice",
  HIDDEN = "Hidden",
  HARD_ROCK = "HardRock",
  SUDDEN_DEATH = "SuddenDeath",
  DOUBLE_TIME = "DoubleTime",
  RELAX = "Relax",
  HALF_TIME = "HalfTime",
  NIGHTCORE = "Nightcore",
  FLASHLIGHT = "Flashlight",
  AUTOPLAY = "Autoplay",
  SPUN_OUT = "SpunOut",
  RELAX2 = "Relax2",
  PERFECT = "Perfect",
  KEY4 = "Key4",
  KEY5 = "Key5",
  KEY6 = "Key6",
  KEY7 = "Key7",
  KEY8 = "Key8",
  FADE_IN = "FadeIn",
  RANDOM = "Random",
  CINEMA = "Cinema",
  TARGET = "Target",
  KEY9 = "Key9",
  KEY_COOP = "KeyCoop",
  KEY1 = "Key1",
  KEY3 = "Key3",
  KEY2 = "Key2",
  SCORE_V2 = "ScoreV2",
  MIRROR = "Mirror",
}

export type MostPlayedBeatmapResponse = {
  id: number;
  beatmapset_id: number;
  hash: string;
  version: string;
  status: BeatmapStatusWeb;
  star_rating_osu: number;
  star_rating_taiko: number;
  star_rating_ctb: number;
  star_rating_mania: number;
  total_length: number;
  max_combo: number;
  accuracy?: number | null;
  ar?: number | null;
  bpm: number;
  convert: boolean;
  count_circles: number;
  count_sliders: number;
  count_spinners: number;
  cs: number;
  deleted_at?: string | null;
  drain?: number | null;
  hit_length: number;
  is_scoreable: boolean;
  is_ranked: boolean;
  last_updated: string;
  mode_int: number;
  mode: GameMode;
  ranked: number;
  title?: string | null;
  artist?: string | null;
  creator?: string | null;
  creator_id: number;
  beatmap_nominator_user?: UserResponse;
  play_count: number;
};

export type MostPlayedResponse = {
  most_played: MostPlayedBeatmapResponse[];
  total_count: number;
};

export type PerformanceAttributes = {
  difficulty: DifficultyAttributes;
  effectiveMissCount?: number | null;
  estimatedUnstableRate?: number | null;
  pp: number;
  ppAccuracy?: number | null;
  ppAim?: number | null;
  ppDifficulty?: number | null;
  ppFlashlight?: number | null;
  ppSpeed?: number | null;
  state: ScoreState;
};

export type PlayHistorySnapshotResponse = {
  play_count: number;
  saved_at: string;
};

export type PlayHistorySnapshotsResponse = {
  total_count: number;
  snapshots: PlayHistorySnapshotResponse[];
};

export type PreviousUsernamesResponse = {
  usernames: string[];
};

export type ProblemDetailsResponseType = {
  type?: string | null;
  title?: string | null;
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
  traceId?: string | null;
  errors?: unknown;
};

export type RateLimits = {
  total_limit: number;
  remaining_calls: number;
};

export type RefreshTokenRequest = {
  refresh_token: string;
};

export type RefreshTokenResponse = {
  token: string;
  expires_in: number;
};

export type RegisterRequest = {
  username: string;
  password: string;
  email: string;
};

export type ResetPasswordRequest = {
  new_password: string;
};

export enum ScoreProcessingErrorCode {
  UNEXPECTED = "Unexpected",
  BEATMAP_NOT_FOUND = "BeatmapNotFound",
  DUPLICATE_SCORE = "DuplicateScore",
  PP_CALCULATION_FAILED = "PpCalculationFailed",
  REPLAY_MISSING = "ReplayMissing",
  INVALID_MODS = "InvalidMods",
  BANNABLE_PP_THRESHOLD = "BannablePpThreshold",
  INVALID_CHECKSUMS = "InvalidChecksums",
  USER_NOT_FOUND = "UserNotFound",
  USER_STATS_NOT_FOUND = "UserStatsNotFound",
  USER_GRADES_NOT_FOUND = "UserGradesNotFound",
  TRANSACTION_FAILED = "TransactionFailed",
  PARSED_SCORE_INVALID = "ParsedScoreInvalid",
  CANCELLED_BY_OPERATOR = "CancelledByOperator",
  INVALID_SCORE_STATE = "InvalidScoreState",
}

export enum ScoreProcessingEventType {
  RECALCULATION_REQUESTED = "RecalculationRequested",
  RESTORE_REQUESTED = "RestoreRequested",
  DELETE_REQUESTED = "DeleteRequested",
  SUBMISSION_ENQUEUED = "SubmissionEnqueued",
  CANCELLED = "Cancelled",
  REQUEUED = "Requeued",
  BULK_REQUESTED = "BulkRequested",
}

export type ScoreProcessingPreviewResponse = {
  score: AdminScoreResponse;
  active_task?: ScoreProcessingTaskResponse;
};

export type ScoreProcessingStatsResponse = {
  pending: number;
  processing: number;
  failed: number;
  estimated_pending_completion_seconds?: number | null;
};

export enum ScoreProcessingStatus {
  PENDING = "Pending",
  PROCESSING = "Processing",
  FAILED = "Failed",
}

export type ScoreProcessingTaskResponse = {
  id: number;
  task_type: ScoreTaskType;
  status: ScoreProcessingStatus;
  priority: number;
  retry_count: number;
  error_code?: ScoreProcessingErrorCode;
  error_message?: string | null;
  next_retry_at?: string | null;
  created_at: string;
  score_id?: number | null;
  score?: AdminScoreResponse;
};

export type ScoreProcessingTasksResponse = {
  tasks: ScoreProcessingTaskResponse[];
  total_count: number;
};

export type ScoreResponse = {
  accuracy: number;
  beatmap_id: number;
  count_100: number;
  count_300: number;
  count_50: number;
  count_geki: number;
  count_katu: number;
  count_miss: number;
  game_mode: GameMode;
  game_mode_extended: GameMode;
  grade: string;
  id: number;
  is_passed: boolean;
  has_replay: boolean;
  leaderboard_rank?: number | null;
  max_combo: number;
  mods?: string | null;
  mods_int?: number | null;
  is_perfect: boolean;
  performance_points: number;
  total_score: number;
  user_id: number;
  when_played: string;
  user: UserResponse;
};

export enum ScoreSortType {
  DATE = "Date",
  PERFORMANCE = "Performance",
}

export type ScoreState = {
  maxCombo?: number | null;
  osuLargeTickHits?: number | null;
  osuSmallTickHits?: number | null;
  sliderEndHits?: number | null;
  nGeki?: number | null;
  nKatu?: number | null;
  n300?: number | null;
  n100?: number | null;
  n50?: number | null;
  misses?: number | null;
};

export enum ScoreTableType {
  BEST = "Best",
  RECENT = "Recent",
  TOP = "Top",
}

export enum ScoreTaskType {
  SUBMISSION = "Submission",
  RECALCULATION = "Recalculation",
  RESTORE = "Restore",
  DELETE = "Delete",
}

export type ScoresResponse = {
  scores: ScoreResponse[];
  total_count: number;
};

export type SolarSystemVersionResponse = {
  is_running_under_solar_system: boolean;
  solar_system_version?: string | null;
};

export type StatsSnapshotResponse = {
  country_rank: number;
  pp: number;
  global_rank: number;
  saved_at: string;
};

export type StatsSnapshotsResponse = {
  total_count: number;
  snapshots: StatsSnapshotResponse[];
};

export type StatusResponse = {
  is_online: boolean;
  is_on_maintenance: boolean;
  users_online: number;
  current_users_online?: UserResponse[] | null;
  total_users: number;
  recent_users?: UserResponse[] | null;
  total_scores?: number | null;
  total_restrictions?: number | null;
};

export enum SubmissionStatus {
  FAILED = "Failed",
  SUBMITTED = "Submitted",
  BEST = "Best",
  DELETED = "Deleted",
  UNKNOWN = "Unknown",
}

export type TokenRequest = {
  username: string;
  password: string;
};

export type TokenResponse = {
  token: string;
  refresh_token: string;
  expires_in: number;
};

export type UpdateBeatmapsCustomStatusRequest = {
  ids: number[];
  status: BeatmapStatusWeb;
};

export enum UpdateFriendshipStatusAction {
  ADD = "Add",
  REMOVE = "Remove",
}

export enum UserBadge {
  DEVELOPER = "Developer",
  ADMIN = "Admin",
  BAT = "Bat",
  BOT = "Bot",
  SUPPORTER = "Supporter",
}

export enum UserEventType {
  GAME_LOGIN = "GameLogin",
  WEB_LOGIN = "WebLogin",
  REGISTER = "Register",
  CHANGE_EMAIL = "ChangeEmail",
  CHANGE_PASSWORD = "ChangePassword",
  CHANGE_AVATAR = "ChangeAvatar",
  CHANGE_BANNER = "ChangeBanner",
  CHANGE_USERNAME = "ChangeUsername",
  CHANGE_COUNTRY = "ChangeCountry",
  CHANGE_PRIVILEGE = "ChangePrivilege",
  CHANGE_METADATA = "ChangeMetadata",
  CHANGE_DESCRIPTION = "ChangeDescription",
  CHANGE_DEFAULT_GAME_MODE = "ChangeDefaultGameMode",
  CHANGE_FRIENDSHIP_STATUS = "ChangeFriendshipStatus",
  RESTRICT = "Restrict",
  UNRESTRICT = "Unrestrict",
}

export type UserMedalResponse = {
  readonly id: number;
  readonly name: string;
  readonly description: string;
  readonly unlocked_at?: string | null;
};

export type UserMetadataResponse = {
  playstyle: UserPlaystyle[];
  location: string;
  interest: string;
  occupation: string;
  telegram: string;
  twitch: string;
  twitter: string;
  discord: string;
  website: string;
};

export enum UserPlaystyle {
  NONE = "None",
  MOUSE = "Mouse",
  KEYBOARD = "Keyboard",
  TABLET = "Tablet",
  TOUCH_SCREEN = "TouchScreen",
}

export enum UserPrivilege {
  USER = "User",
  SUPPORTER = "Supporter",
  BAT = "Bat",
  ADMIN = "Admin",
  DEVELOPER = "Developer",
  SUPER_USER = "SuperUser",
  SERVER_BOT = "ServerBot",
}

export type UserRelationsCountersResponse = {
  followers: number;
  following: number;
};

export type UserResponse = {
  user_id: number;
  username: string;
  description?: string | null;
  country_code: CountryCode;
  register_date: string;
  avatar_url: string;
  banner_url: string;
  last_online_time: string;
  restricted: boolean;
  silenced_until?: string | null;
  default_gamemode: GameMode;
  badges: UserBadge[];
  user_status: string;
};

export type UserSensitiveResponse = {
  user_id: number;
  username: string;
  email: string;
  privilege: UserPrivilege[];
  description?: string | null;
  country_code: CountryCode;
  register_date: string;
  avatar_url: string;
  banner_url: string;
  last_online_time: string;
  restricted: boolean;
  silenced_until?: string | null;
  default_gamemode: GameMode;
  badges: UserBadge[];
  user_status: string;
};

export type UserStatsResponse = {
  user_id: number;
  gamemode: GameMode;
  accuracy: number;
  total_score: number;
  ranked_score: number;
  play_count: number;
  pp: number;
  rank: number;
  country_rank: number;
  max_combo: number;
  play_time: number;
  total_hits: number;
  best_global_rank: number;
  best_global_rank_date: string;
  best_country_rank: number;
  best_country_rank_date: string;
};

export type UserWithStats = {
  user: UserResponse;
  stats: UserStatsResponse;
};

export type UserWithStatsResponse = {
  user: UserResponse;
  stats?: UserStatsResponse;
};

export type UsernameChangeRequest = {
  new_username: string;
};

export type UsersSensitiveListResponse = {
  users: UserSensitiveResponse[];
  total_count: number;
};

export enum WebSocketEventType {
  NEW_SCORE_SUBMITTED = "NewScoreSubmitted",
  CUSTOM_BEATMAP_STATUS_CHANGED = "CustomBeatmapStatusChanged",
}

export type WebSocketMessage = {
  messageType: WebSocketEventType;
  readonly data: string;
};

export type PostAuthTokenData = {
  body?: TokenRequest;
  path?: never;
  query?: never;
  url: "/auth/token";
};

export type PostAuthTokenErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
};

export type PostAuthTokenError = PostAuthTokenErrors[keyof PostAuthTokenErrors];

export type PostAuthTokenResponses = {
  /**
     * OK
     */
  200: TokenResponse;
};

export type PostAuthTokenResponse = PostAuthTokenResponses[keyof PostAuthTokenResponses];

export type PostAuthRefreshData = {
  body?: RefreshTokenRequest;
  path?: never;
  query?: never;
  url: "/auth/refresh";
};

export type PostAuthRefreshErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
  /**
     * OK
     */
  200: RefreshTokenResponse;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthRegisterData = {
  body?: RegisterRequest;
  path?: never;
  query?: never;
  url: "/auth/register";
};

export type PostAuthRegisterErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
  /**
     * OK
     */
  200: TokenResponse;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type GetPingData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ping";
};

export type GetPingErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
};

export type GetPingError = GetPingErrors[keyof GetPingErrors];

export type GetPingResponses = {
  /**
     * OK
     */
  200: string;
};

export type GetPingResponse = GetPingResponses[keyof GetPingResponses];

export type GetLimitsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/limits";
};

export type GetLimitsErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
};

export type GetLimitsError = GetLimitsErrors[keyof GetLimitsErrors];

export type GetLimitsResponses = {
  /**
     * OK
     */
  200: LimitsResponse;
};

export type GetLimitsResponse = GetLimitsResponses[keyof GetLimitsResponses];

export type GetStatusData = {
  body?: never;
  path?: never;
  query?: {
    detailed?: boolean;
    includeRecentUsers?: boolean;
  };
  url: "/status";
};

export type GetStatusErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
};

export type GetStatusError = GetStatusErrors[keyof GetStatusErrors];

export type GetStatusResponses = {
  /**
     * OK
     */
  200: StatusResponse;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetVersionData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/version";
};

export type GetVersionErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
};

export type GetVersionError = GetVersionErrors[keyof GetVersionErrors];

export type GetVersionResponses = {
  /**
     * OK
     */
  200: SolarSystemVersionResponse;
};

export type GetVersionResponse = GetVersionResponses[keyof GetVersionResponses];

export type GetBeatmapByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/beatmap/{id}";
};

export type GetBeatmapByIdErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetBeatmapByIdError = GetBeatmapByIdErrors[keyof GetBeatmapByIdErrors];

export type GetBeatmapByIdResponses = {
  /**
     * OK
     */
  200: BeatmapResponse;
};

export type GetBeatmapByIdResponse = GetBeatmapByIdResponses[keyof GetBeatmapByIdResponses];

export type GetBeatmapsetByBeatmapSetByIdData = {
  body?: never;
  path: {
    id: number;
    beatmapSet: string;
  };
  query?: never;
  url: "/beatmapset/{beatmapSet}/{id}";
};

export type GetBeatmapsetByBeatmapSetByIdErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetBeatmapsetByBeatmapSetByIdError = GetBeatmapsetByBeatmapSetByIdErrors[keyof GetBeatmapsetByBeatmapSetByIdErrors];

export type GetBeatmapsetByBeatmapSetByIdResponses = {
  /**
     * OK
     */
  200: BeatmapResponse;
};

export type GetBeatmapsetByBeatmapSetByIdResponse = GetBeatmapsetByBeatmapSetByIdResponses[keyof GetBeatmapsetByBeatmapSetByIdResponses];

export type GetBeatmapByIdPpData = {
  body?: never;
  path: {
    id: number;
  };
  query?: {
    mods?: Mods[];
    mode?: GameMode;
    combo?: number;
    misses?: number;
    accuracy?: number;
  };
  url: "/beatmap/{id}/pp";
};

export type GetBeatmapByIdPpErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetBeatmapByIdPpError = GetBeatmapByIdPpErrors[keyof GetBeatmapByIdPpErrors];

export type GetBeatmapByIdPpResponses = {
  /**
     * OK
     */
  200: PerformanceAttributes;
};

export type GetBeatmapByIdPpResponse = GetBeatmapByIdPpResponses[keyof GetBeatmapByIdPpResponses];

export type GetBeatmapsetByBeatmapSetByIdPpData = {
  body?: never;
  path: {
    id: number;
    beatmapSet: string;
  };
  query?: {
    mods?: Mods[];
    mode?: GameMode;
    combo?: number;
    misses?: number;
    accuracy?: number;
  };
  url: "/beatmapset/{beatmapSet}/{id}/pp";
};

export type GetBeatmapsetByBeatmapSetByIdPpErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetBeatmapsetByBeatmapSetByIdPpError = GetBeatmapsetByBeatmapSetByIdPpErrors[keyof GetBeatmapsetByBeatmapSetByIdPpErrors];

export type GetBeatmapsetByBeatmapSetByIdPpResponses = {
  /**
     * OK
     */
  200: PerformanceAttributes;
};

export type GetBeatmapsetByBeatmapSetByIdPpResponse = GetBeatmapsetByBeatmapSetByIdPpResponses[keyof GetBeatmapsetByBeatmapSetByIdPpResponses];

export type GetBeatmapByIdLeaderboardData = {
  body?: never;
  path: {
    id: number;
  };
  query: {
    mode: GameMode;
    mods?: Mods[];
    limit?: number;
  };
  url: "/beatmap/{id}/leaderboard";
};

export type GetBeatmapByIdLeaderboardErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetBeatmapByIdLeaderboardError = GetBeatmapByIdLeaderboardErrors[keyof GetBeatmapByIdLeaderboardErrors];

export type GetBeatmapByIdLeaderboardResponses = {
  /**
     * OK
     */
  200: ScoresResponse;
};

export type GetBeatmapByIdLeaderboardResponse = GetBeatmapByIdLeaderboardResponses[keyof GetBeatmapByIdLeaderboardResponses];

export type GetBeatmapsetByBeatmapSetByIdLeaderboardData = {
  body?: never;
  path: {
    id: number;
    beatmapSet: string;
  };
  query: {
    mode: GameMode;
    mods?: Mods[];
    limit?: number;
  };
  url: "/beatmapset/{beatmapSet}/{id}/leaderboard";
};

export type GetBeatmapsetByBeatmapSetByIdLeaderboardErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetBeatmapsetByBeatmapSetByIdLeaderboardError = GetBeatmapsetByBeatmapSetByIdLeaderboardErrors[keyof GetBeatmapsetByBeatmapSetByIdLeaderboardErrors];

export type GetBeatmapsetByBeatmapSetByIdLeaderboardResponses = {
  /**
     * OK
     */
  200: ScoresResponse;
};

export type GetBeatmapsetByBeatmapSetByIdLeaderboardResponse = GetBeatmapsetByBeatmapSetByIdLeaderboardResponses[keyof GetBeatmapsetByBeatmapSetByIdLeaderboardResponses];

export type GetBeatmapsetByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/beatmapset/{id}";
};

export type GetBeatmapsetByIdErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetBeatmapsetByIdError = GetBeatmapsetByIdErrors[keyof GetBeatmapsetByIdErrors];

export type GetBeatmapsetByIdResponses = {
  /**
     * OK
     */
  200: BeatmapSetResponse;
};

export type GetBeatmapsetByIdResponse = GetBeatmapsetByIdResponses[keyof GetBeatmapsetByIdResponses];

export type GetBeatmapsetByIdHypeData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/beatmapset/{id}/hype";
};

export type GetBeatmapsetByIdHypeErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetBeatmapsetByIdHypeError = GetBeatmapsetByIdHypeErrors[keyof GetBeatmapsetByIdHypeErrors];

export type GetBeatmapsetByIdHypeResponses = {
  /**
     * OK
     */
  200: BeatmapSetHypeCountResponse;
};

export type GetBeatmapsetByIdHypeResponse = GetBeatmapsetByIdHypeResponses[keyof GetBeatmapsetByIdHypeResponses];

export type PostBeatmapsetByIdHypeData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/beatmapset/{id}/hype";
};

export type PostBeatmapsetByIdHypeErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type PostBeatmapsetByIdHypeError = PostBeatmapsetByIdHypeErrors[keyof PostBeatmapsetByIdHypeErrors];

export type PostBeatmapsetByIdHypeResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type GetBeatmapsetGetHypedSetsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    page?: number;
  };
  url: "/beatmapset/get-hyped-sets";
};

export type GetBeatmapsetGetHypedSetsErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetBeatmapsetGetHypedSetsError = GetBeatmapsetGetHypedSetsErrors[keyof GetBeatmapsetGetHypedSetsErrors];

export type GetBeatmapsetGetHypedSetsResponses = {
  /**
     * OK
     */
  200: HypedBeatmapSetsResponse;
};

export type GetBeatmapsetGetHypedSetsResponse = GetBeatmapsetGetHypedSetsResponses[keyof GetBeatmapsetGetHypedSetsResponses];

export type GetBeatmapsetByIdEventsData = {
  body?: never;
  path: {
    id: number;
  };
  query?: {
    limit?: number;
    page?: number;
  };
  url: "/beatmapset/{id}/events";
};

export type GetBeatmapsetByIdEventsErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetBeatmapsetByIdEventsError = GetBeatmapsetByIdEventsErrors[keyof GetBeatmapsetByIdEventsErrors];

export type GetBeatmapsetByIdEventsResponses = {
  /**
     * OK
     */
  200: BeatmapSetEventsResponse;
};

export type GetBeatmapsetByIdEventsResponse = GetBeatmapsetByIdEventsResponses[keyof GetBeatmapsetByIdEventsResponses];

export type GetBeatmapsetEventsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    page?: number;
  };
  url: "/beatmapset/events";
};

export type GetBeatmapsetEventsErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetBeatmapsetEventsError = GetBeatmapsetEventsErrors[keyof GetBeatmapsetEventsErrors];

export type GetBeatmapsetEventsResponses = {
  /**
     * OK
     */
  200: BeatmapSetEventsResponse;
};

export type GetBeatmapsetEventsResponse = GetBeatmapsetEventsResponses[keyof GetBeatmapsetEventsResponses];

export type GetBeatmapsetByIdFavouritedData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/beatmapset/{id}/favourited";
};

export type GetBeatmapsetByIdFavouritedErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type GetBeatmapsetByIdFavouritedError = GetBeatmapsetByIdFavouritedErrors[keyof GetBeatmapsetByIdFavouritedErrors];

export type GetBeatmapsetByIdFavouritedResponses = {
  /**
     * OK
     */
  200: FavouritedResponse;
};

export type GetBeatmapsetByIdFavouritedResponse = GetBeatmapsetByIdFavouritedResponses[keyof GetBeatmapsetByIdFavouritedResponses];

export type PostBeatmapsetByIdFavouritedData = {
  body?: EditBeatmapsetFavouriteStatusRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/beatmapset/{id}/favourited";
};

export type PostBeatmapsetByIdFavouritedErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type PostBeatmapsetByIdFavouritedError = PostBeatmapsetByIdFavouritedErrors[keyof PostBeatmapsetByIdFavouritedErrors];

export type PostBeatmapsetByIdFavouritedResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostBeatmapUpdateCustomStatusData = {
  body?: UpdateBeatmapsCustomStatusRequest;
  path?: never;
  query?: never;
  url: "/beatmap/update-custom-status";
};

export type PostBeatmapUpdateCustomStatusErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type PostBeatmapUpdateCustomStatusError = PostBeatmapUpdateCustomStatusErrors[keyof PostBeatmapUpdateCustomStatusErrors];

export type PostBeatmapUpdateCustomStatusResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type GetBeatmapsetSearchData = {
  body?: never;
  path?: never;
  query?: {
    query?: string;
    status?: BeatmapStatusWeb[];
    mode?: GameMode;
    searchByCustomStatus?: boolean;
    limit?: number;
    page?: number;
  };
  url: "/beatmapset/search";
};

export type GetBeatmapsetSearchErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetBeatmapsetSearchError = GetBeatmapsetSearchErrors[keyof GetBeatmapsetSearchErrors];

export type GetBeatmapsetSearchResponses = {
  /**
     * OK
     */
  200: BeatmapSetsResponse;
};

export type GetBeatmapsetSearchResponse = GetBeatmapsetSearchResponses[keyof GetBeatmapsetSearchResponses];

export type GetScoreByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/score/{id}";
};

export type GetScoreByIdErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetScoreByIdError = GetScoreByIdErrors[keyof GetScoreByIdErrors];

export type GetScoreByIdResponses = {
  /**
     * OK
     */
  200: ScoreResponse;
};

export type GetScoreByIdResponse = GetScoreByIdResponses[keyof GetScoreByIdResponses];

export type GetScoreByIdReplayData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/score/{id}/replay";
};

export type GetScoreByIdReplayErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetScoreByIdReplayError = GetScoreByIdReplayErrors[keyof GetScoreByIdReplayErrors];

export type GetScoreByIdReplayResponses = {
  /**
     * OK
     */
  200: Blob | File;
};

export type GetScoreByIdReplayResponse = GetScoreByIdReplayResponses[keyof GetScoreByIdReplayResponses];

export type GetScoreTopData = {
  body?: never;
  path?: never;
  query?: {
    mode?: GameMode;
    limit?: number;
    page?: number;
  };
  url: "/score/top";
};

export type GetScoreTopErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
};

export type GetScoreTopError = GetScoreTopErrors[keyof GetScoreTopErrors];

export type GetScoreTopResponses = {
  /**
     * OK
     */
  200: ScoresResponse;
};

export type GetScoreTopResponse = GetScoreTopResponses[keyof GetScoreTopResponses];

export type GetScoreProcessingData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    status?: ScoreProcessingStatus;
    task_type?: ScoreTaskType;
    score_id?: number;
    task_id?: number;
  };
  url: "/score-processing";
};

export type GetScoreProcessingErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Forbidden
     */
  403: ProblemDetailsResponseType;
};

export type GetScoreProcessingError = GetScoreProcessingErrors[keyof GetScoreProcessingErrors];

export type GetScoreProcessingResponses = {
  /**
     * OK
     */
  200: ScoreProcessingTasksResponse;
};

export type GetScoreProcessingResponse = GetScoreProcessingResponses[keyof GetScoreProcessingResponses];

export type PostScoreProcessingData = {
  body?: CreateScoreProcessingTaskRequest;
  path?: never;
  query?: never;
  url: "/score-processing";
};

export type PostScoreProcessingErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Forbidden
     */
  403: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
  /**
     * Conflict
     */
  409: ProblemDetailsResponseType;
};

export type PostScoreProcessingError = PostScoreProcessingErrors[keyof PostScoreProcessingErrors];

export type PostScoreProcessingResponses = {
  /**
     * OK
     */
  200: unknown;
  /**
     * Created
     */
  201: ScoreProcessingTaskResponse;
};

export type PostScoreProcessingResponse = PostScoreProcessingResponses[keyof PostScoreProcessingResponses];

export type GetScoreProcessingStatsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/score-processing/stats";
};

export type GetScoreProcessingStatsErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Forbidden
     */
  403: ProblemDetailsResponseType;
};

export type GetScoreProcessingStatsError = GetScoreProcessingStatsErrors[keyof GetScoreProcessingStatsErrors];

export type GetScoreProcessingStatsResponses = {
  /**
     * OK
     */
  200: ScoreProcessingStatsResponse;
};

export type GetScoreProcessingStatsResponse = GetScoreProcessingStatsResponses[keyof GetScoreProcessingStatsResponses];

export type GetScoreProcessingByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/score-processing/{id}";
};

export type GetScoreProcessingByIdErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Forbidden
     */
  403: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetScoreProcessingByIdError = GetScoreProcessingByIdErrors[keyof GetScoreProcessingByIdErrors];

export type GetScoreProcessingByIdResponses = {
  /**
     * OK
     */
  200: ScoreProcessingTaskResponse;
};

export type GetScoreProcessingByIdResponse = GetScoreProcessingByIdResponses[keyof GetScoreProcessingByIdResponses];

export type GetScoreProcessingScoreByScoreIdData = {
  body?: never;
  path: {
    scoreId: number;
  };
  query?: never;
  url: "/score-processing/score/{scoreId}";
};

export type GetScoreProcessingScoreByScoreIdErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Forbidden
     */
  403: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetScoreProcessingScoreByScoreIdError = GetScoreProcessingScoreByScoreIdErrors[keyof GetScoreProcessingScoreByScoreIdErrors];

export type GetScoreProcessingScoreByScoreIdResponses = {
  /**
     * OK
     */
  200: ScoreProcessingPreviewResponse;
};

export type GetScoreProcessingScoreByScoreIdResponse = GetScoreProcessingScoreByScoreIdResponses[keyof GetScoreProcessingScoreByScoreIdResponses];

export type PostScoreProcessingByIdCancelData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/score-processing/{id}/cancel";
};

export type PostScoreProcessingByIdCancelErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Forbidden
     */
  403: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
  /**
     * Conflict
     */
  409: ProblemDetailsResponseType;
};

export type PostScoreProcessingByIdCancelError = PostScoreProcessingByIdCancelErrors[keyof PostScoreProcessingByIdCancelErrors];

export type PostScoreProcessingByIdCancelResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostScoreProcessingByIdRequeueData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/score-processing/{id}/requeue";
};

export type PostScoreProcessingByIdRequeueErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Forbidden
     */
  403: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
  /**
     * Conflict
     */
  409: ProblemDetailsResponseType;
};

export type PostScoreProcessingByIdRequeueError = PostScoreProcessingByIdRequeueErrors[keyof PostScoreProcessingByIdRequeueErrors];

export type PostScoreProcessingByIdRequeueResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostScoreProcessingBulkData = {
  body?: BulkScoreProcessingRequest;
  path?: never;
  query?: never;
  url: "/score-processing/bulk";
};

export type PostScoreProcessingBulkErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Forbidden
     */
  403: ProblemDetailsResponseType;
};

export type PostScoreProcessingBulkError = PostScoreProcessingBulkErrors[keyof PostScoreProcessingBulkErrors];

export type PostScoreProcessingBulkResponses = {
  /**
     * OK
     */
  200: BulkScoreProcessingResultResponse;
};

export type PostScoreProcessingBulkResponse = PostScoreProcessingBulkResponses[keyof PostScoreProcessingBulkResponses];

export type PostScoreProcessingBulkByFilterData = {
  body?: BulkScoreProcessingByFilterRequest;
  path?: never;
  query?: never;
  url: "/score-processing/bulk-by-filter";
};

export type PostScoreProcessingBulkByFilterErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Forbidden
     */
  403: ProblemDetailsResponseType;
};

export type PostScoreProcessingBulkByFilterError = PostScoreProcessingBulkByFilterErrors[keyof PostScoreProcessingBulkByFilterErrors];

export type PostScoreProcessingBulkByFilterResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type GetScoreProcessingEventsData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    types?: ScoreProcessingEventType[];
    score_id?: number;
  };
  url: "/score-processing/events";
};

export type GetScoreProcessingEventsErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Forbidden
     */
  403: ProblemDetailsResponseType;
};

export type GetScoreProcessingEventsError = GetScoreProcessingEventsErrors[keyof GetScoreProcessingEventsErrors];

export type GetScoreProcessingEventsResponses = {
  /**
     * OK
     */
  200: EventScoreProcessingListResponse;
};

export type GetScoreProcessingEventsResponse = GetScoreProcessingEventsResponses[keyof GetScoreProcessingEventsResponses];

export type GetUserByIdData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}";
};

export type GetUserByIdErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
  /**
     * OK
     */
  200: UserResponse;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type GetUserByIdSensitiveData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/sensitive";
};

export type GetUserByIdSensitiveErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByIdSensitiveError = GetUserByIdSensitiveErrors[keyof GetUserByIdSensitiveErrors];

export type GetUserByIdSensitiveResponses = {
  /**
     * OK
     */
  200: UserSensitiveResponse;
};

export type GetUserByIdSensitiveResponse = GetUserByIdSensitiveResponses[keyof GetUserByIdSensitiveResponses];

export type GetUserByIdByModeData = {
  body?: never;
  path: {
    id: number;
    mode: GameMode;
  };
  query?: never;
  url: "/user/{id}/{mode}";
};

export type GetUserByIdByModeErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByIdByModeError = GetUserByIdByModeErrors[keyof GetUserByIdByModeErrors];

export type GetUserByIdByModeResponses = {
  /**
     * OK
     */
  200: UserWithStatsResponse;
};

export type GetUserByIdByModeResponse = GetUserByIdByModeResponses[keyof GetUserByIdByModeResponses];

export type GetUserSelfData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/user/self";
};

export type GetUserSelfErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type GetUserSelfError = GetUserSelfErrors[keyof GetUserSelfErrors];

export type GetUserSelfResponses = {
  /**
     * OK
     */
  200: UserResponse;
};

export type GetUserSelfResponse = GetUserSelfResponses[keyof GetUserSelfResponses];

export type GetUserSelfByModeData = {
  body?: never;
  path: {
    mode: GameMode;
  };
  query?: never;
  url: "/user/self/{mode}";
};

export type GetUserSelfByModeErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type GetUserSelfByModeError = GetUserSelfByModeErrors[keyof GetUserSelfByModeErrors];

export type GetUserSelfByModeResponses = {
  /**
     * OK
     */
  200: UserWithStatsResponse;
};

export type GetUserSelfByModeResponse = GetUserSelfByModeResponses[keyof GetUserSelfByModeResponses];

export type PostUserEditDescriptionData = {
  body?: EditDescriptionRequest;
  path?: never;
  query?: never;
  url: "/user/edit/description";
};

export type PostUserEditDescriptionErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserEditDescriptionError = PostUserEditDescriptionErrors[keyof PostUserEditDescriptionErrors];

export type PostUserEditDescriptionResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserByIdEditDescriptionData = {
  body?: EditDescriptionRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/edit/description";
};

export type PostUserByIdEditDescriptionErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserByIdEditDescriptionError = PostUserByIdEditDescriptionErrors[keyof PostUserByIdEditDescriptionErrors];

export type PostUserByIdEditDescriptionResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserEditDefaultGamemodeData = {
  body?: EditDefaultGameModeRequest;
  path?: never;
  query?: never;
  url: "/user/edit/default-gamemode";
};

export type PostUserEditDefaultGamemodeErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserEditDefaultGamemodeError = PostUserEditDefaultGamemodeErrors[keyof PostUserEditDefaultGamemodeErrors];

export type PostUserEditDefaultGamemodeResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserByIdEditRestrictionData = {
  body?: EditUserRestrictionRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/edit/restriction";
};

export type PostUserByIdEditRestrictionErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserByIdEditRestrictionError = PostUserByIdEditRestrictionErrors[keyof PostUserByIdEditRestrictionErrors];

export type PostUserByIdEditRestrictionResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserByIdEditIgnoreLoginDataData = {
  body?: EditIgnoreLoginDataRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/edit/ignore-login-data";
};

export type PostUserByIdEditIgnoreLoginDataErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type PostUserByIdEditIgnoreLoginDataError = PostUserByIdEditIgnoreLoginDataErrors[keyof PostUserByIdEditIgnoreLoginDataErrors];

export type PostUserByIdEditIgnoreLoginDataResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserEditHidePreviousUsernameData = {
  body?: EditHidePreviousUsernameRequest;
  path?: never;
  query?: never;
  url: "/user/edit/hide-previous-username";
};

export type PostUserEditHidePreviousUsernameErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserEditHidePreviousUsernameError = PostUserEditHidePreviousUsernameErrors[keyof PostUserEditHidePreviousUsernameErrors];

export type PostUserEditHidePreviousUsernameResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type GetUserByUserIdGraphData = {
  body?: never;
  path: {
    userId: number;
  };
  query: {
    mode: GameMode;
  };
  url: "/user/{userId}/graph";
};

export type GetUserByUserIdGraphErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByUserIdGraphError = GetUserByUserIdGraphErrors[keyof GetUserByUserIdGraphErrors];

export type GetUserByUserIdGraphResponses = {
  /**
     * OK
     */
  200: StatsSnapshotsResponse;
};

export type GetUserByUserIdGraphResponse = GetUserByUserIdGraphResponses[keyof GetUserByUserIdGraphResponses];

export type GetUserByUserIdPlayHistoryGraphData = {
  body?: never;
  path: {
    userId: number;
  };
  query?: never;
  url: "/user/{userId}/play-history-graph";
};

export type GetUserByUserIdPlayHistoryGraphErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByUserIdPlayHistoryGraphError = GetUserByUserIdPlayHistoryGraphErrors[keyof GetUserByUserIdPlayHistoryGraphErrors];

export type GetUserByUserIdPlayHistoryGraphResponses = {
  /**
     * OK
     */
  200: PlayHistorySnapshotsResponse;
};

export type GetUserByUserIdPlayHistoryGraphResponse = GetUserByUserIdPlayHistoryGraphResponses[keyof GetUserByUserIdPlayHistoryGraphResponses];

export type GetUserByIdScoresData = {
  body?: never;
  path: {
    id: number;
  };
  query?: {
    mode?: GameMode;
    type?: ScoreTableType;
    limit?: number;
    page?: number;
  };
  url: "/user/{id}/scores";
};

export type GetUserByIdScoresErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByIdScoresError = GetUserByIdScoresErrors[keyof GetUserByIdScoresErrors];

export type GetUserByIdScoresResponses = {
  /**
     * OK
     */
  200: ScoresResponse;
};

export type GetUserByIdScoresResponse = GetUserByIdScoresResponses[keyof GetUserByIdScoresResponses];

export type GetUserByIdScoresAdminData = {
  body?: never;
  path: {
    id: number;
  };
  query?: {
    mode?: GameMode;
    mods?: Mods[];
    submission_status?: SubmissionStatus;
    beatmap_status?: BeatmapStatus;
    submitted_from?: string;
    submitted_to?: string;
    sort?: ScoreSortType;
    limit?: number;
    page?: number;
  };
  url: "/user/{id}/scores/admin";
};

export type GetUserByIdScoresAdminErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByIdScoresAdminError = GetUserByIdScoresAdminErrors[keyof GetUserByIdScoresAdminErrors];

export type GetUserByIdScoresAdminResponses = {
  /**
     * OK
     */
  200: AdminScoresResponse;
};

export type GetUserByIdScoresAdminResponse = GetUserByIdScoresAdminResponses[keyof GetUserByIdScoresAdminResponses];

export type GetUserByIdMostplayedData = {
  body?: never;
  path: {
    id: number;
  };
  query?: {
    mode?: GameMode;
    limit?: number;
    page?: number;
  };
  url: "/user/{id}/mostplayed";
};

export type GetUserByIdMostplayedErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByIdMostplayedError = GetUserByIdMostplayedErrors[keyof GetUserByIdMostplayedErrors];

export type GetUserByIdMostplayedResponses = {
  /**
     * OK
     */
  200: MostPlayedResponse;
};

export type GetUserByIdMostplayedResponse = GetUserByIdMostplayedResponses[keyof GetUserByIdMostplayedResponses];

export type GetUserByIdFavouritesData = {
  body?: never;
  path: {
    id: number;
  };
  query?: {
    limit?: number;
    page?: number;
  };
  url: "/user/{id}/favourites";
};

export type GetUserByIdFavouritesErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByIdFavouritesError = GetUserByIdFavouritesErrors[keyof GetUserByIdFavouritesErrors];

export type GetUserByIdFavouritesResponses = {
  /**
     * OK
     */
  200: BeatmapSetsResponse;
};

export type GetUserByIdFavouritesResponse = GetUserByIdFavouritesResponses[keyof GetUserByIdFavouritesResponses];

export type GetUserByIdPreviousUsernamesData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/previous-usernames";
};

export type GetUserByIdPreviousUsernamesErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByIdPreviousUsernamesError = GetUserByIdPreviousUsernamesErrors[keyof GetUserByIdPreviousUsernamesErrors];

export type GetUserByIdPreviousUsernamesResponses = {
  /**
     * OK
     */
  200: PreviousUsernamesResponse;
};

export type GetUserByIdPreviousUsernamesResponse = GetUserByIdPreviousUsernamesResponses[keyof GetUserByIdPreviousUsernamesResponses];

export type GetUserLeaderboardData = {
  body?: never;
  path?: never;
  query?: {
    mode?: GameMode;
    type?: LeaderboardSortType;
    limit?: number;
    page?: number;
  };
  url: "/user/leaderboard";
};

export type GetUserLeaderboardErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserLeaderboardError = GetUserLeaderboardErrors[keyof GetUserLeaderboardErrors];

export type GetUserLeaderboardResponses = {
  /**
     * OK
     */
  200: LeaderboardResponse;
};

export type GetUserLeaderboardResponse = GetUserLeaderboardResponses[keyof GetUserLeaderboardResponses];

export type GetUserSearchData = {
  body?: never;
  path?: never;
  query: {
    query: string;
    limit?: number;
    page?: number;
  };
  url: "/user/search";
};

export type GetUserSearchErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
};

export type GetUserSearchError = GetUserSearchErrors[keyof GetUserSearchErrors];

export type GetUserSearchResponses = {
  /**
     * OK
     */
  200: UserResponse[];
};

export type GetUserSearchResponse = GetUserSearchResponses[keyof GetUserSearchResponses];

export type GetUserSearchListData = {
  body?: never;
  path?: never;
  query?: {
    query?: string;
    limit?: number;
    page?: number;
  };
  url: "/user/search/list";
};

export type GetUserSearchListErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
};

export type GetUserSearchListError = GetUserSearchListErrors[keyof GetUserSearchListErrors];

export type GetUserSearchListResponses = {
  /**
     * OK
     */
  200: UsersSensitiveListResponse;
};

export type GetUserSearchListResponse = GetUserSearchListResponses[keyof GetUserSearchListResponses];

export type GetUserFriendsData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    page?: number;
  };
  url: "/user/friends";
};

export type GetUserFriendsErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type GetUserFriendsError = GetUserFriendsErrors[keyof GetUserFriendsErrors];

export type GetUserFriendsResponses = {
  /**
     * OK
     */
  200: FriendsResponse;
};

export type GetUserFriendsResponse = GetUserFriendsResponses[keyof GetUserFriendsResponses];

export type GetUserByIdFriendsData = {
  body?: never;
  path: {
    id: number;
  };
  query?: {
    limit?: number;
    page?: number;
  };
  url: "/user/{id}/friends";
};

export type GetUserByIdFriendsErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type GetUserByIdFriendsError = GetUserByIdFriendsErrors[keyof GetUserByIdFriendsErrors];

export type GetUserByIdFriendsResponses = {
  /**
     * OK
     */
  200: FriendsResponse;
};

export type GetUserByIdFriendsResponse = GetUserByIdFriendsResponses[keyof GetUserByIdFriendsResponses];

export type GetUserFollowersData = {
  body?: never;
  path?: never;
  query?: {
    limit?: number;
    page?: number;
  };
  url: "/user/followers";
};

export type GetUserFollowersErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type GetUserFollowersError = GetUserFollowersErrors[keyof GetUserFollowersErrors];

export type GetUserFollowersResponses = {
  /**
     * OK
     */
  200: FollowersResponse;
};

export type GetUserFollowersResponse = GetUserFollowersResponses[keyof GetUserFollowersResponses];

export type GetUserByIdFollowersData = {
  body?: never;
  path: {
    id: number;
  };
  query?: {
    limit?: number;
    page?: number;
  };
  url: "/user/{id}/followers";
};

export type GetUserByIdFollowersErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type GetUserByIdFollowersError = GetUserByIdFollowersErrors[keyof GetUserByIdFollowersErrors];

export type GetUserByIdFollowersResponses = {
  /**
     * OK
     */
  200: FollowersResponse;
};

export type GetUserByIdFollowersResponse = GetUserByIdFollowersResponses[keyof GetUserByIdFollowersResponses];

export type GetUserByIdFriendStatusData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/friend/status";
};

export type GetUserByIdFriendStatusErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByIdFriendStatusError = GetUserByIdFriendStatusErrors[keyof GetUserByIdFriendStatusErrors];

export type GetUserByIdFriendStatusResponses = {
  /**
     * OK
     */
  200: FriendStatusResponse;
};

export type GetUserByIdFriendStatusResponse = GetUserByIdFriendStatusResponses[keyof GetUserByIdFriendStatusResponses];

export type PostUserByIdFriendStatusData = {
  body?: EditFriendshipStatusRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/friend/status";
};

export type PostUserByIdFriendStatusErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type PostUserByIdFriendStatusError = PostUserByIdFriendStatusErrors[keyof PostUserByIdFriendStatusErrors];

export type PostUserByIdFriendStatusResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type GetUserByIdEventsData = {
  body?: never;
  path: {
    id: number;
  };
  query?: {
    limit?: number;
    page?: number;
    query?: string;
    types?: UserEventType[];
  };
  url: "/user/{id}/events";
};

export type GetUserByIdEventsErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type GetUserByIdEventsError = GetUserByIdEventsErrors[keyof GetUserByIdEventsErrors];

export type GetUserByIdEventsResponses = {
  /**
     * OK
     */
  200: EventUsersResponse;
};

export type GetUserByIdEventsResponse = GetUserByIdEventsResponses[keyof GetUserByIdEventsResponses];

export type GetUserInventoryItemData = {
  body?: never;
  path?: never;
  query: {
    type: ItemType;
  };
  url: "/user/inventory/item";
};

export type GetUserInventoryItemErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserInventoryItemError = GetUserInventoryItemErrors[keyof GetUserInventoryItemErrors];

export type GetUserInventoryItemResponses = {
  /**
     * OK
     */
  200: InventoryItemResponse;
};

export type GetUserInventoryItemResponse = GetUserInventoryItemResponses[keyof GetUserInventoryItemResponses];

export type GetUserByIdFriendsCountData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/friends/count";
};

export type GetUserByIdFriendsCountErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByIdFriendsCountError = GetUserByIdFriendsCountErrors[keyof GetUserByIdFriendsCountErrors];

export type GetUserByIdFriendsCountResponses = {
  /**
     * OK
     */
  200: UserRelationsCountersResponse;
};

export type GetUserByIdFriendsCountResponse = GetUserByIdFriendsCountResponses[keyof GetUserByIdFriendsCountResponses];

export type GetUserByIdMedalsData = {
  body?: never;
  path: {
    id: number;
  };
  query: {
    mode: GameMode;
  };
  url: "/user/{id}/medals";
};

export type GetUserByIdMedalsErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
};

export type GetUserByIdMedalsError = GetUserByIdMedalsErrors[keyof GetUserByIdMedalsErrors];

export type GetUserByIdMedalsResponses = {
  /**
     * OK
     */
  200: MedalsResponse;
};

export type GetUserByIdMedalsResponse = GetUserByIdMedalsResponses[keyof GetUserByIdMedalsResponses];

export type GetUserByIdGradesData = {
  body?: never;
  path: {
    id: number;
  };
  query: {
    mode: GameMode;
  };
  url: "/user/{id}/grades";
};

export type GetUserByIdGradesErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByIdGradesError = GetUserByIdGradesErrors[keyof GetUserByIdGradesErrors];

export type GetUserByIdGradesResponses = {
  /**
     * OK
     */
  200: GradesResponse;
};

export type GetUserByIdGradesResponse = GetUserByIdGradesResponses[keyof GetUserByIdGradesResponses];

export type GetUserByIdMetadataData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/metadata";
};

export type GetUserByIdMetadataErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type GetUserByIdMetadataError = GetUserByIdMetadataErrors[keyof GetUserByIdMetadataErrors];

export type GetUserByIdMetadataResponses = {
  /**
     * OK
     */
  200: UserMetadataResponse;
};

export type GetUserByIdMetadataResponse = GetUserByIdMetadataResponses[keyof GetUserByIdMetadataResponses];

export type PostUserByIdEditMetadataData = {
  body?: EditUserMetadataRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/edit/metadata";
};

export type PostUserByIdEditMetadataErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type PostUserByIdEditMetadataError = PostUserByIdEditMetadataErrors[keyof PostUserByIdEditMetadataErrors];

export type PostUserByIdEditMetadataResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserByIdEditPrivilegeData = {
  body?: EditUserPrivilegeRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/edit/privilege";
};

export type PostUserByIdEditPrivilegeErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type PostUserByIdEditPrivilegeError = PostUserByIdEditPrivilegeErrors[keyof PostUserByIdEditPrivilegeErrors];

export type PostUserByIdEditPrivilegeResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserEditMetadataData = {
  body?: EditUserMetadataRequest;
  path?: never;
  query?: never;
  url: "/user/edit/metadata";
};

export type PostUserEditMetadataErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Not Found
     */
  404: ProblemDetailsResponseType;
};

export type PostUserEditMetadataError = PostUserEditMetadataErrors[keyof PostUserEditMetadataErrors];

export type PostUserEditMetadataResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserByIdUploadAvatarData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/upload/avatar";
};

export type PostUserByIdUploadAvatarErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserByIdUploadAvatarError = PostUserByIdUploadAvatarErrors[keyof PostUserByIdUploadAvatarErrors];

export type PostUserByIdUploadAvatarResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserUploadAvatarData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/user/upload/avatar";
};

export type PostUserUploadAvatarErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserUploadAvatarError = PostUserUploadAvatarErrors[keyof PostUserUploadAvatarErrors];

export type PostUserUploadAvatarResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserByIdUploadBannerData = {
  body?: never;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/upload/banner";
};

export type PostUserByIdUploadBannerErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserByIdUploadBannerError = PostUserByIdUploadBannerErrors[keyof PostUserByIdUploadBannerErrors];

export type PostUserByIdUploadBannerResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserUploadBannerData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/user/upload/banner";
};

export type PostUserUploadBannerErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserUploadBannerError = PostUserUploadBannerErrors[keyof PostUserUploadBannerErrors];

export type PostUserUploadBannerResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserByIdPasswordChangeData = {
  body?: ResetPasswordRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/password/change";
};

export type PostUserByIdPasswordChangeErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserByIdPasswordChangeError = PostUserByIdPasswordChangeErrors[keyof PostUserByIdPasswordChangeErrors];

export type PostUserByIdPasswordChangeResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserPasswordChangeData = {
  body?: ChangePasswordRequest;
  path?: never;
  query?: never;
  url: "/user/password/change";
};

export type PostUserPasswordChangeErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserPasswordChangeError = PostUserPasswordChangeErrors[keyof PostUserPasswordChangeErrors];

export type PostUserPasswordChangeResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserByIdUsernameChangeData = {
  body?: UsernameChangeRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/username/change";
};

export type PostUserByIdUsernameChangeErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserByIdUsernameChangeError = PostUserByIdUsernameChangeErrors[keyof PostUserByIdUsernameChangeErrors];

export type PostUserByIdUsernameChangeResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserUsernameChangeData = {
  body?: UsernameChangeRequest;
  path?: never;
  query?: never;
  url: "/user/username/change";
};

export type PostUserUsernameChangeErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserUsernameChangeError = PostUserUsernameChangeErrors[keyof PostUserUsernameChangeErrors];

export type PostUserUsernameChangeResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserByIdCountryChangeData = {
  body?: CountryChangeRequest;
  path: {
    id: number;
  };
  query?: never;
  url: "/user/{id}/country/change";
};

export type PostUserByIdCountryChangeErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserByIdCountryChangeError = PostUserByIdCountryChangeErrors[keyof PostUserByIdCountryChangeErrors];

export type PostUserByIdCountryChangeResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type PostUserCountryChangeData = {
  body?: CountryChangeRequest;
  path?: never;
  query?: never;
  url: "/user/country/change";
};

export type PostUserCountryChangeErrors = {
  /**
     * Bad Request
     */
  400: ProblemDetailsResponseType;
  /**
     * Unauthorized
     */
  401: ProblemDetailsResponseType;
};

export type PostUserCountryChangeError = PostUserCountryChangeErrors[keyof PostUserCountryChangeErrors];

export type PostUserCountryChangeResponses = {
  /**
     * OK
     */
  200: unknown;
};

export type GetWsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/ws";
};

export type GetWsResponses = {
  /**
     * OK
     */
  200: WebSocketMessage;
};

export type GetWsResponse = GetWsResponses[keyof GetWsResponses];

export type ClientOptions = {
  baseUrl: "https://api.sunrise.local" | (string & {});
};
